name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      
      - name: make .env
        run: |
          touch .env
          echo ${{ secrets.NEXT_PUBLIC_API_URI }} >> .env
          cat .env
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          NEXT_PUBLIC_API_URI: NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/samplefront:${{ github.sha }} --build-arg NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/samplefront:${{ github.sha }}
